name: learngpt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.5
  - pytorch-cuda=12.4
  - matplotlib
  - numpy
  - pyarrow>=17
  - pyyaml
  - pip
  - pip:
      - tokenizers>=0.20,<1
